name: build-mkdocs
description: Parametized mkdocs building

inputs:
  site_url:
    description: Set `MKDOCS_SITE_URL` env var
    required: true

  working_dir:
    description: Parent directory that contains mkdocs.yml
    required: true

  output_dir:
    description: Where we will output the resulting webpage
    required: true

  upload_artifact:
    description: Upload `github-pages` artifact?
    default: "false"

outputs:
  artifact_id:
    description: "Artifact id uploaded (is an empty string in case of `upload_artifact: false`)"
    value: ""

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2

    - name: Configure Poetry
      working-directory: ${{ inputs.working_dir }}
      shell: bash
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - name: Poetry install deps
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: poetry install

    - name: Build book in English
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      env:
        MKDOCS_SITE_URL: ${{ inputs.site_url }}
        _OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |
        source .venv/bin/activate
        mkdocs build --verbose -d $_OUTPUT_DIR

    - name: Upload artifact
      if: ${{ inputs.upload_artifact == 'true' }}
      uses: actions/upload-pages-artifact@v3
      id: upload-artifact
      with:
        path: ${{ inputs.output_dir }}

    - name: Output artifact id
      shell: bash
      run: echo "artifact_id=${{ steps.upload-artifact.outputs.artifact_id }}" >> $GITHUB_OUTPUT
