[include]
paths = ["/etc/ublue-os/topgrade.toml"]

[misc]
no_self_update = true
only = ["system", "flatpak", "brew_cask", "brew_formula", "firmware", "custom_commands"]
ignore_failures = ["flatpak", "brew_cask", "brew_formula", "firmware", "custom_commands"]
assume_yes = true
no_retry = false

[linux]
rpm_ostree = true
