name: Bug Report
description: Report an issue about using Bazzite
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! The Bazzite team will NEVER ask you to download arbritary files from the internet, help us keep GitHub clean by reporting phishing links.
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
      value: "When I entered 2 + 2, I got the answer 6."
    validations:
      required: true
  - type: textarea
    id: expected-bahavior
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: What were you expecting to happen? IE: I expected 2+2 to equal 4!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Output of `rpm-ostree status`
      description: Please run `rpm-ostree status` and paste the output here.
      render: shell
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: Hardware
      description: Please provide further information about your hardware. If reporting a bug on a handheld device, please provide the output of the following - `cat /sys/devices/virtual/dmi/id/product_name`
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Extra information or context
      description: Add any other context about the problem here.
