#!/usr/bin/bash
#
#     %%%%%%====%%%%%%%%%%            
#   %%%%%%%%    %%%%%%%%%%%%%%        
#  %%%%%%%%%    %%%%%%%%%%%%%%%%      
#  %%%%%%%%%    %%%%%%%%%%%%%%%###    
#  %%%%%%%%%    %%%%%%%%%%%%%######   
#  ==                  =======######  
#  ==                  =========##### 
#  %%%%%%%%%    %%%%%%%####======#####
#  %%%%%%%%%    %%%%%#######=====#####
#  %%%%%%%%%    %%%#########=====#####
#  %%%%%%%%%    %%##########=====#####
#  %%%%%%%%%====###########=====######
#   %%%%%%%%====#########======###### 
#    %%%%%%%=====#####========######  
#     %%%%###===============#######   
#      %#######==========#########    
#        #######################      
#          ###################        
#              ###########            
#
# Welcome to Bazzite! If you're looking to
# build your own, we highly recommend you
# use our custom image template. Forking
# the main repo provides more control, but
# is often unnecessary.
#
# https://github.com/ublue-os/image-template

set -ouex pipefail

################
# DECK BUILDS
################

rsync -av /ctx/system_files/deck/shared/ /ctx/system_files/deck/${BASE_IMAGE_NAME}/ /

# Setup Copr repos
dnf5 -y copr enable ublue-os/akmods && \
dnf5 -y copr enable kylegospo/bazzite && \
dnf5 -y copr enable kylegospo/bazzite-multilib && \
dnf5 -y copr enable kylegospo/LatencyFleX && \
dnf5 -y copr enable kylegospo/obs-vkcapture && \
dnf5 -y copr enable kylegospo/wallpaper-engine-kde-plugin && \
dnf5 -y copr enable hhd-dev/hhd && \
dnf5 -y copr enable ycollet/audinux

# Configure KDE & GNOME
dnf5 -y remove \
    jupiter-sd-mounting-btrfs && \
if grep -q "kinoite" <<< "${BASE_IMAGE_NAME}"; then \
    dnf5 -y remove \
        steamdeck-kde-presets-desktop && \
   dnf5 -y install \
        steamdeck-kde-presets \
; else \
    dnf5 -y install \
        steamdeck-gnome-presets \
        gnome-shell-extension-caribou-blocker \
        sddm \
; fi

# Install new packages
# Dock updater - done manually due to proprietary parts preventing it from being on Copr
# Neptune firmware - done manually due to "TBD" license on needed audio firmware
dnf5 -y install \
    jupiter-fan-control \
    jupiter-hw-support-btrfs \
    steamdeck-dsp \
    powerbuttond \
    hhd \
    hhd-ui \
    adjustor \
    acpica-tools \
    vpower \
    ds-inhibit \
    steam_notif_daemon \
    sdgyrodsu \
    ibus-pinyin \
    ibus-table-chinese-cangjie \
    ibus-table-chinese-quick \
    socat \
    zstd \
    zenity \
    newt \
    qt6-qtvirtualkeyboard \
    xorg-x11-server-Xvfb \
    python-vdf \
    python-crcmod && \
git clone https://gitlab.com/evlaV/jupiter-dock-updater-bin.git \
    --depth 1 \
    /tmp/jupiter-dock-updater-bin && \
mv -v /tmp/jupiter-dock-updater-bin/packaged/usr/lib/jupiter-dock-updater /usr/libexec/jupiter-dock-updater && \
rm -rf /tmp/jupiter-dock-updater-bin && \
ln -s /usr/bin/steamos-logger /usr/bin/steamos-info && \
ln -s /usr/bin/steamos-logger /usr/bin/steamos-notice && \
ln -s /usr/bin/steamos-logger /usr/bin/steamos-warning

# Install Steam Deck patched UPower, remove Tuned GUI
dnf5 -y swap \
--repo copr:copr.fedorainfracloud.org:kylegospo:bazzite \
    upower upower

# Install Gamescope Session & Supporting changes
# Add bootstrap_steam.tar.gz used by gamescope-session (Thanks GE & Nobara Project!)
mkdir -p /usr/share/gamescope-session-plus/ && \
curl -Lo /usr/share/gamescope-session-plus/bootstrap_steam.tar.gz https://large-package-sources.nobaraproject.org/bootstrap_steam.tar.gz && \
dnf5 -y install \
    gamescope-session-plus \
    gamescope-session-steam

# Cleanup & Finalize
/ctx/build_files/image-info && \
mkdir -p "/etc/xdg/autostart" && \
mv "/etc/skel/.config/autostart/steam.desktop" "/etc/xdg/autostart/steam.desktop" && \
sed -i 's@Exec=waydroid first-launch@Exec=/usr/bin/waydroid-launcher first-launch\nX-Steam-Library-Capsule=/usr/share/applications/Waydroid/capsule.png\nX-Steam-Library-Hero=/usr/share/applications/Waydroid/hero.png\nX-Steam-Library-Logo=/usr/share/applications/Waydroid/logo.png\nX-Steam-Library-StoreCapsule=/usr/share/applications/Waydroid/store-logo.png\nX-Steam-Controller-Template=Desktop@g' /usr/share/applications/Waydroid.desktop && \
if grep -q "kinoite" <<< "${BASE_IMAGE_NAME}"; then \
    sed -i 's/Exec=.*/Exec=systemctl start return-to-gamemode.service/' /etc/skel/Desktop/Return.desktop && \
    mkdir -p /usr/share/ublue-os/backup && \
    mv /usr/share/applications/com.github.maliit.keyboard.desktop /usr/share/ublue-os/backup/com.github.maliit.keyboard.desktop \
; fi && \
sed -i 's@\[Desktop Entry\]@\[Desktop Entry\]\nNoDisplay=true@g' /usr/share/applications/input-remapper-gtk.desktop && \
cp "/usr/share/ublue-os/firstboot/yafti.yml" "/etc/yafti.yml" && \
dnf5 copr disable -y ublue-os/akmods && \
dnf5 copr disable -y kylegospo/bazzite && \
dnf5 copr disable -y kylegospo/bazzite-multilib && \
dnf5 copr disable -y kylegospo/LatencyFleX && \
dnf5 copr disable -y kylegospo/obs-vkcapture && \
dnf5 copr disable -y kylegospo/wallpaper-engine-kde-plugin && \
dnf5 copr disable -y hhd-dev/hhd && \
dnf5 copr disable -y ycollet/audinux && \
if grep -q "silverblue" <<< "${BASE_IMAGE_NAME}"; then \
    systemctl disable gdm.service && \
    systemctl enable sddm.service \
; fi && \
if grep -q "silverblue" <<< "${BASE_IMAGE_NAME}"; then \
  mkdir -p "/usr/share/ublue-os/dconfs/deck-silverblue/" && \
  cp "/usr/share/glib-2.0/schemas/zz0-"*"-bazzite-deck-silverblue-"*".gschema.override" "/usr/share/ublue-os/dconfs/deck-silverblue/" && \
  find "/etc/dconf/db/distro.d/" -maxdepth 1 -type f -exec cp {} "/usr/share/ublue-os/dconfs/deck-silverblue/" \; && \
  dconf-override-converter to-dconf "/usr/share/ublue-os/dconfs/deck-silverblue/zz0-"*"-bazzite-deck-silverblue-"*".gschema.override" && \
  rm "/usr/share/ublue-os/dconfs/deck-silverblue/zz0-"*"-bazzite-deck-silverblue-"*".gschema.override" \
; else \
  systemctl disable usr-share-sddm-themes.mount \
; fi && \
mkdir -p /tmp/bazzite-schema-test && \
find "/usr/share/glib-2.0/schemas/" -type f ! -name "*.gschema.override" -exec cp {} "/tmp/bazzite-schema-test/" \; && \
cp "/usr/share/glib-2.0/schemas/zz0-"*".gschema.override" "/tmp/bazzite-schema-test/" && \
glib-compile-schemas --strict /tmp/bazzite-schema-test && \
glib-compile-schemas /usr/share/glib-2.0/schemas &>/dev/null && \
rm -r /tmp/bazzite-schema-test && \
{ rm -v /usr/share/applications/bazzite-steam-bpm.desktop || true; } && \
systemctl enable bazzite-autologin.service && \
systemctl enable wireplumber-workaround.service && \
systemctl enable wireplumber-sysconf.service && \
systemctl enable pipewire-workaround.service && \
systemctl enable pipewire-sysconf.service && \
systemctl enable ds-inhibit.service && \
systemctl enable cec-onboot.service && \
systemctl enable cec-onpoweroff.service && \
systemctl enable cec-onsleep.service && \
systemctl enable bazzite-tdpfix.service && \
systemctl enable bazzite-grub-boot-success.timer && \
systemctl enable bazzite-grub-boot-success.service && \
systemctl --global disable sdgyrodsu.service && \
systemctl --global disable grub-boot-success.timer && \
systemctl disable grub-boot-indeterminate.service && \
systemctl disable input-remapper.service && \
systemctl disable ublue-update.timer && \
systemctl disable jupiter-fan-control.service && \
systemctl disable vpower.service && \
systemctl disable jupiter-biosupdate.service && \
systemctl disable jupiter-controller-update.service && \
systemctl disable batterylimit.service

/ctx/build_files/cleanup
/ctx/build_files/finalize
