#!/usr/bin/env bash
# KDE specifc modifications

set -eoux pipefail

dnf5 -y install \
  qt \
  steamdeck-kde-presets-desktop \
  rom-properties-kf6 \
  fcitx5-chewing \
  fcitx5-chinese-addons \
  fcitx5-hangul \
  fcitx5-m17n \
  fcitx5-mozc \
  fcitx5-table-extra \
  kcm-fcitx5 \
  gnome-disk-utility \
  krunner-bazaar \
  krunner-yafti \
  krdc \
  tesseract-langpack-spa \
  tesseract-langpack-deu \
  tesseract-langpack-jpn \
  tesseract-langpack-jpn_vert \
  tesseract-langpack-fra \
  tesseract-langpack-por \
  tesseract-langpack-rus \
  tesseract-langpack-ita \
  tesseract-langpack-nld \
  tesseract-langpack-pol \
  tesseract-langpack-tur \
  tesseract-langpack-chi_sim \
  tesseract-langpack-chi_sim_vert \
  tesseract-langpack-ces \
  tesseract-langpack-ell \
  plasma-oxygen \
  oxygen-icon-theme

dnf5 -y remove \
  plasma-drkonqi \
  plasma-welcome{,-fedora} \
  plasma-discover-kns \
  kcharselect \
  kde-partitionmanager \
  plasma-discover{,-libs}

sed -i '$r /usr/share/plasma/shells/org.kde.plasma.desktop/contents/updates/bazzite-pins.js' /usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js
ln -sf /usr/share/wallpapers/convergence.jxl /usr/share/backgrounds/default.jxl
ln -sf /usr/share/wallpapers/convergence.jxl /usr/share/backgrounds/default-dark.jxl
rm -f /usr/share/backgrounds/default.xml

mkdir -p /usr/share/wallpapers/bazzite/convergence/contents/images
ln -s /usr/share/wallpapers/convergence.jxl /usr/share/wallpapers/bazzite/convergence/contents/images/3940x2160.jxl

# TODO: Figure out why this is needed and upstream this to fedora
setcap 'cap_net_admin+ep' /usr/bin/kdeconnectd
