#!/usr/bin/bash

set -eoux pipefail

dnf5 config-manager setopt keepcache=0
dnf5 clean all >/dev/null 2>&1 || true

if [[ -d /tmp ]]; then
    find /tmp -mindepth 1 -maxdepth 1 -exec rm -rf -- {} + || true
fi
if [[ -d /run ]]; then
    find /run -mindepth 1 -maxdepth 1 ! -path /run/systemd -exec rm -rf -- {} + || true
fi
if [[ -d /run/systemd ]]; then
    find /run/systemd -mindepth 1 -maxdepth 1 ! -name resolve -exec rm -rf -- {} + || true
fi
find /var/* -maxdepth 0 -type d \! -name cache -exec rm -fr {} \;
mkdir -p /var/cache
find /var/cache -mindepth 1 -maxdepth 1 -exec rm -rf -- {} + || true
mkdir -p /var/tmp
chmod -R 1777 /var/tmp

# Copy entries into /usr/lib/passwd and /usr/lib/group
if [ -f /etc/passwd ]; then
    out=$(grep -v "root" /etc/passwd) || true
    if [ -n "$out" ]; then
        echo
        echo Moving the following passwd users to /usr/lib/passwd
        echo "$out"
        echo "$out" >> /usr/lib/passwd
        echo "root:x:0:0:root:/root:/bin/bash" > /etc/passwd
    fi
fi
if [ -f /etc/group ]; then
    out=$(grep -v "root\|wheel" /etc/group) || true
    if [ -n "$out" ]; then
        echo
        echo Moving the following group entries to /usr/lib/group
        echo "$out"
        echo "$out" >> /usr/lib/group
        echo "root:x:0:" > /etc/group
        echo "wheel:x:10:" >> /etc/group
    fi
fi

# Extra lock files created by container processes that might cause issues
rm -rf \
    /etc/.pwd.lock \
    /etc/passwd- \
    /etc/group- \
    /etc/shadow- \
    /etc/gshadow- \
    /etc/subuid- \
    /etc/subgid- \
