#!/bin/bash

#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is derived from greenboot.
#
#  greenboot is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

set -eo pipefail

maxbootcount=2

if ! /usr/bin/grub2-editenv - set boot_counter="$maxbootcount"; then
    exit 1
fi

echo "<3>GRUB2 environment variables have been set for system upgrade. Max boot attempts is $maxbootcount"