#!/usr/bin/bash

if [ "$1" == "root" ]; then
	echo "Do not run this for root."
	exit 0
fi

# Enable HHD
systemctl enable --now hhd@$(systemd-escape $1).service
# Ensure HHD is never running for the root user
systemctl disable --now hhd@root.service
