#!/usr/bin/bash

set -e
SYS_ID="$(cat /sys/devices/virtual/dmi/id/product_name)"

if [[ ":Jupiter:" =~ ":$SYS_ID:" || ":Galileo:" =~ ":$SYS_ID:" ]]; then
  # Rotate the builtin screen every time so it's the right way around.
  xrandr --output "eDP" --rotate "right"
fi
