#!/usr/bin/bash

function short_session_recover {
    mkdir -p ~/.local/share
    # remove some caches and stateful things known to cause Steam to fail to start if corrupt
    rm -rf --one-file-system ~/.local/share/Steam/config/widevine
    # extract the steam bootstrap to potentially fix the issue the next boot
    if [[ -f "/usr/share/gamescope-session-plus/bootstrap_steam.tar.gz" ]]; then
        tar xf /usr/share/gamescope-session-plus/bootstrap_steam.tar.gz -C ~/.local/share
        setup_custom_videos
    fi
    # change session to desktop as fallback
    steamos-session-select desktop
}

CLIENTCMD="/home/bazzite/Desktop/supertuxkart-0.9.1-linux/run_game.sh"
