#!/usr/bin/bash
# Returns true for hardware that is supported by Handycon exclusively.
SYS_ID="$(cat /sys/devices/virtual/dmi/id/product_name)"
if [[ ":AYANEO GEEK:AYANEO 2:AYANEO 2S:AOKZOE A1 AR07:G1619-04:Win600:" =~ ":$SYS_ID:" ]]; then
	exit 0
else
	exit 1
fi
