#!/usr/bin/bash

SYS_ID="$(/usr/libexec/hwsupport/sysid 2>/dev/null || true)"

# Legion Go
# Loki Max
# Zeenix Pro (rebranded Loki Max)
# AYANEO Air Plus
# Onexfly (8840u)
if [[ ":83E1:Loki Max:Zeenix Pro:AIR Plus:ONEXPLAYER F1:ONEXPLAYER F1L:ONEXPLAYER F1 EVA-01:" == *":${SYS_ID}:"* && -n "${SYS_ID}" ]]; then
	exit 0
fi

exit 1
