#!/usr/bin/bash
# Returns true for Valve handhelds
SYS_ID="$("/usr/libexec/hwsupport/sysid" 2>/dev/null || true)"
if [[ "${SYS_ID}" == "Jupiter" || "${SYS_ID}" == "Galileo" ]]; then
	exit 0
fi

exit 1
