_default:
    just --list

build_messages_pot:
    MDBOOK_OUTPUT='{"xgettext": {}}' \
        mdbook build -d po

add_translation LANG: build_messages_pot
    msginit -i po/messages.pot -l {{LANG}} -o po/{{LANG}}.po

prep_translation LANG:
    #!/usr/bin/bash
    mdbook clean
    just build_messages_pot
    [[ ! -f po/{{LANG}}.po ]] && just add add_translation {{LANG}}
    msgmerge --update po/{{LANG}}.po po/messages.pot