#!/bin/bash

# Start yafti-go in background
~/.local/bin/yafti-go &
YAFTI_PID=$!

# Launch surf browser (lightweight WebKit browser) with X11 backend
GDK_BACKEND=x11 /bin/surf http://localhost:3169

# Kill yafti-go when surf window is closed
kill $YAFTI_PID
