#!/bin/bash
set_snapper_defaults () {
    # Set the config to 0 retention, has to be changed by user
    snapper set-config "TIMELINE_MIN_AGE=1800"
    snapper set-config "TIMELINE_LIMIT_DAILY=0"
    snapper set-config "TIMELINE_LIMIT_HOURLY=0"
    snapper set-config "TIMELINE_LIMIT_MONTHLY=0"
    snapper set-config "TIMELINE_LIMIT_WEEKLY=0"
    snapper set-config "TIMELINE_LIMIT_QUARTERLY=0"
    snapper set-config "TIMELINE_LIMIT_YEARLY=0"

    # Set manual/boot retention to 0
    snapper set-config "NUMBER_MIN_AGE=1800"
    snapper set-config "NUMBER_LIMIT=0"
    snapper set-config "NUMBER_LIMIT_IMPORTANT=0"

    # Enable cleanup
    systemctl enable --now snapper-cleanup.timer
}

# Create an empty config for the home subvolume if a root config does not exist
if ! snapper get-config >/dev/null 2>&1; then
    # Make a config for /var/home as /home will not work
    snapper create-config /var/home

    # Set the snapper config settings
    set_snapper_defaults

    # Disable the timeline and boot timers
    systemctl disable --now snapper-timeline.timer
    systemctl disable --now snapper-boot.timer
fi

# Check for invalid config and fix it and remove incorrect snapshots
if [ $(systemctl is-enabled snapper-timeline.timer) == "enabled" ] && [ $(snapper --no-headers --csvout get-config | grep "TIMELINE_LIMIT_YEARLY,10") == "TIMELINE_LIMIT_YEARLY,10" ]; then
    # Set snapper config settings
    set_snapper_defaults

    # Disable services that should be enabled by the user (how did these even get enabled?)
    systemctl disable --now snapper-timeline.timer
    systemctl disable --now snapper-boot.timer

    # Do a cleanup and remove incorrect snapshots
    snapper cleanup timeline
    snapper cleanup number
fi

## Safeguards against snapper somehow enabling its timers by itself?
# Disable snapper-timeline timer if it has been enabled with no changes to the config
if [ $(systemctl is-enabled snapper-timeline.timer) == "enabled" ] && [ $(sudo snapper --no-headers --csvout get-config | grep -P 'TIMELINE_LIMIT_(DAILY|HOURLY|MONTHLY|WEEKLY|QUARTERLY|YEARLY),0' | wc -l) == "6" ]; then
    systemctl disable --now snapper-timeline.timer
    systemctl enable --now snapper-cleanup.timer
    snapper cleanup timeline
fi

# Disable snapper-boot timer if it has been enabled with no changes to the config
if [ $(systemctl is-enabled snapper-boot.timer) == "enabled" ] && [ $(sudo snapper --no-headers --csvout get-config | grep 'NUMBER_LIMIT,0' | wc -l) == "1" ]; then
    systemctl disable --now snapper-boot.timer
    systemctl enable --now snapper-cleanup.timer
    snapper cleanup number
fi
