#!/usr/bin/bash

systemctl unmask wpa_supplicant.service

if [ -f /etc/NetworkManager/conf.d/99-valve-wifi-backend.conf ]; then
  # This file was created by earlier versions of steamos-manager, make sure it's removed. We handle this ourselves.
  rm -f /etc/NetworkManager/conf.d/99-valve-wifi-backend.conf
fi

if [ -f /etc/NetworkManager/conf.d/iwd.conf ]; then
  # This file was created by earlier versions of bazzite-hardware-setup, make sure it's removed.
  rm -f /etc/NetworkManager/conf.d/iwd.conf
fi