#!/usr/bin/bash
shopt -s nullglob

echo "Looking for updates..."

# Flatpak Firefox
for firefox_gnome_theme in "$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox/"*".default"*"/chrome/firefox-gnome-theme/"; do
  if [ -d "$firefox_gnome_theme" ]; then
    echo "Firefox theme found, pulling latest with git"
    cd "$firefox_gnome_theme"
    git pull
    echo "Update complete"
  fi
done

# Flatpak Thunderbird
for thunderbird_gnome_theme in "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird/"*".default"*"/chrome/thunderbird-gnome-theme/"; do
  if [ -d "$thunderbird_gnome_theme" ]; then
    echo "Thunderbird theme found, pulling latest with git"
    cd "$thunderbird_gnome_theme"
    git pull
    echo "Update complete"
  fi
done

exit 0
