#!/usr/bin/bash
shopt -s nullglob

echo "Looking for updates..."

# Adwaita for Steam
if [ -d "$HOME/homebrew/themes/Adwaita-for-Steam/.git" ]; then
  cd "$HOME/homebrew/themes/Adwaita-for-Steam"
  echo "Adwaita for Steam theme found, pulling latest with git."
  git pull
  echo "Update complete."
fi

# Handheld Controller Glyphs
if [ -d "$HOME/homebrew/themes/handheld-controller-glyphs/.git" ]; then
  cd "$HOME/homebrew/themes/handheld-controller-glyphs"
  echo "handheld-controller-glyphs theme found, pulling latest with git."
  git pull
  echo "Update complete."
fi

exit 0
