on:
  workflow_call:
  workflow_dispatch:
    inputs:
      handwritten:
        description: 'Small changelog about changes in this build:'
      target:
        description: 'Release Branch (e.g., testing). Defaults to branch name.'
permissions: {}

name: Generate Release
jobs:
  generate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout last 500 commits (for <commits> to work)
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 500

      - name: Get target
        id: get-target
        run: |
          TARGET="${{ github.event.inputs.target || github.ref }}"
          TARGET="${TARGET##*/}"
          if [ "$TARGET" = "main" ]; then
            TARGET="stable"
          fi
          echo "target=$TARGET" >> $GITHUB_OUTPUT

      - name: Install ORAS
        uses: oras-project/setup-oras@1d808f7d7f6995cc68b7bf507bfe5c5446e1dc9d # v2.0.1

      - name: Generate Release Text
        id: generate-release
        run: |
          python3 ./.github/workflows/changelog.py \
            "${{ steps.get-target.outputs.target }}" \
            ./output.env ./changelog.md --workdir . --handwritten "${{ github.event.inputs.handwritten }}"
          source ./output.env
          echo "title=${TITLE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          name: ${{ steps.generate-release.outputs.title }}
          tag_name: ${{ steps.generate-release.outputs.tag }}
          body_path: ./changelog.md
          make_latest: ${{ steps.get-target.outputs.target == 'stable' }}
          prerelease: ${{ steps.get-target.outputs.target != 'stable' }}
