name: Just Syntax Check

on: [pull_request]

permissions: {}

jobs:
  just-syntax-check:
    name: Check Just Syntax
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Check just syntax
        uses: ublue-os/just-action@v3
