# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# WARNING: This workflow is meant for emergency use only.
# Under NO CIRCUMSTANCES should this workflow be automatically triggered.
name: Retag image

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  packages: write

on:
  workflow_dispatch:
    inputs:
      old_tag:
        description: "Old tag from which images will be retagged to latest"
        required: true
        type: string

jobs:
  safeguard-timer:
    runs-on: ubuntu-latest
    if: inputs.old_tag != ''
    steps:
      - name: Safeguard wait
        env:
          SLEEP_TIME: "30"
        run: |
          echo "Triggered safeguard."
          echo "You have $SLEEP_TIME seconds to cancel the workflow if you want to cancel retagging."
          sleep $SLEEP_TIME

  retag-images:
    runs-on: ubuntu-latest
    if: inputs.old_tag != ''
    needs: [safeguard-timer]
    steps:
      - uses: Zeglius/ghcr-oci-retagger@72699b478c52cd39103fd4af8b53aaf303b99d6b
        with:
          GITHUB_TOKEN: ${{ github.token }}
          PREFIX: ghcr.io/${{ github.repository_owner }}/
          # TODO: Remove dummy DST_PREFIX whenever we ensure this works.
          DST_PREFIX: ttl.sh/${{ github.repository_owner }}-
          TAG_MAPPINGS: |-
            bazzite:${{ inputs.old_tag }}                           => bazzite:latest
            bazzite-asus-nvidia:${{ inputs.old_tag }}               => bazzite-asus-nvidia:latest
            bazzite-asus-nvidia-open:${{ inputs.old_tag }}          => bazzite-asus-nvidia-open:latest
            bazzite-deck:${{ inputs.old_tag }}                      => bazzite-deck:latest
            bazzite-deck-gnome:${{ inputs.old_tag }}                => bazzite-deck-gnome:latest
            bazzite-deck-nvidia:${{ inputs.old_tag }}               => bazzite-deck-nvidia:latest
            bazzite-deck-nvidia-gnome:${{ inputs.old_tag }}         => bazzite-deck-nvidia-gnome:latest
            bazzite-gnome:${{ inputs.old_tag }}                     => bazzite-gnome:latest
            bazzite-gnome-asus-nvidia:${{ inputs.old_tag }}         => bazzite-gnome-asus-nvidia:latest
            bazzite-gnome-asus-nvidia-open:${{ inputs.old_tag }}    => bazzite-gnome-asus-nvidia-open:latest
            bazzite-gnome-nvidia:${{ inputs.old_tag }}              => bazzite-gnome-nvidia:latest
            bazzite-gnome-nvidia-open:${{ inputs.old_tag }}         => bazzite-gnome-nvidia-open:latest
            bazzite-gnome-surface-nvidia-open:${{ inputs.old_tag }} => bazzite-gnome-surface-nvidia-open:latest
            bazzite-nvidia:${{ inputs.old_tag }}                    => bazzite-nvidia:latest
            bazzite-nvidia-open:${{ inputs.old_tag }}               => bazzite-nvidia-open:latest
            bazzite-surface-nvidia-open:${{ inputs.old_tag }}       => bazzite-surface-nvidia-open:latest
