name: Sign Image

# A workflow to sign an image on demand

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to sign, including the tag'
        required: true

permissions: {}

jobs:
  sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Login to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get digest
        id: get-digest
        env:
          IMAGE_TO_SIGN: ${{ inputs.image }}
        run: |
          digest=$(skopeo inspect docker://$IMAGE_TO_SIGN --format '{{.Digest}}')
          name=$(skopeo inspect docker://$IMAGE_TO_SIGN --format '{{.Name}}')
          echo "DIGEST=$digest" >> $GITHUB_OUTPUT
          echo "NAME=$name" >> $GITHUB_OUTPUT

      - name: Setup Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: 'v2.6.1'

      - name: Sign Image
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_SECRET }}
          IMAGE_NAME: ${{ steps.get-digest.outputs.NAME }}
          IMAGE_DIGEST: ${{ steps.get-digest.outputs.DIGEST }}
        run: |
          cosign sign -y --key env://SIGNING_KEY --new-bundle-format=false $IMAGE_NAME@$IMAGE_DIGEST
